[package]
name = "jira_export"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
dirs = "5.0.1"
futures = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
