[package]
name = "domain"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
chrono = { workspace = true }
humantime-serde = { workspace = true }
serde = { workspace = true }
