[package]
name = "rofi_jira_tracker"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
domain = { path = "../domain" }
reqwest = { workspace = true, features = ["blocking"] }
rofi-mode = "0.3.1"
